import Foundation

// Translate display labels without changing project identifiers or enum raw values.
extension String {
    var chineseUI: String { ChineseUI.labels[self] ?? self }
}

enum ChineseUI {
    static let labels: [String: String] = [
        "3 by 3 Average": "3 × 3 平均",
        "5 by 5 Average": "5 × 5 平均",
        "Actual Pixels": "实际像素",
        "Actual pixels (⌘1)": "实际像素 (⌘1)",
        "Add": "添加",
        "Add Hide-All Mask": "添加隐藏全部的蒙版",
        "Add Layer Mask": "添加图层蒙版",
        "Add Mask": "添加蒙版",
        "Add Noise": "添加杂色",
        "Add Reveal-All Mask": "添加显示全部的蒙版",
        "Add layer effect": "添加图层效果",
        "Add layer mask": "添加图层蒙版",
        "Add layer mask (Option-click for a black mask)": "添加图层蒙版（按住 Option 单击创建黑色蒙版）",
        "Add layer mask revealing the selection (Option-click to hide it)": "添加显示选区的蒙版（按住 Option 单击隐藏选区）",
        "Add to Selection": "添加到选区",
        "Advanced": "高级",
        "Aligned": "对齐",
        "All": "全部",
        "All Layers": "所有图层",
        "Amount": "数量",
        "Anchor": "定位",
        "Angle": "角度",
        "Anti-alias": "消除锯齿",
        "Apply": "应用",
        "Apply Crop": "应用裁剪",
        "Applying…": "正在应用…",
        "Aquas": "浅绿色",
        "Aspect": "宽高比",
        "Auto": "自动",
        "Background": "背景",
        "Background color": "背景色",
        "Balance": "平衡",
        "Based On": "基于",
        "Basic": "基本",
        "Black": "黑色",
        "Black & White": "黑白",
        "Black · Hide": "黑色 · 隐藏",
        "Blacks": "黑色色阶",
        "Blend mode": "混合模式",
        "Blue": "蓝色",
        "Blue Primary": "蓝色原色",
        "Blues": "蓝色",
        "Blur": "模糊",
        "Bottom": "底部",
        "Bottom Right Pixel Color": "右下角像素颜色",
        "Bottom center": "下中",
        "Bottom left": "左下",
        "Bottom right": "右下",
        "Brightness": "亮度",
        "Brush": "画笔",
        "Brush (B) · Eraser (E)": "画笔 (B) · 橡皮擦 (E)",
        "Calibration": "校准",
        "Camera Raw Filter": "Camera Raw 滤镜",
        "Cancel": "取消",
        "Canvas": "画布",
        "Canvas & Layers": "画布与图层",
        "Canvas Only (F)": "仅显示画布 (F)",
        "Canvas Size": "画布大小",
        "Canvas Size…": "画布大小…",
        "Center": "居中",
        "Centimeters": "厘米",
        "Channel": "通道",
        "Clarity": "清晰度",
        "Clear Guides": "清除参考线",
        "Clear Menu": "清除列表",
        "Clear Selection Pixels": "清除选区像素",
        "Clone Stamp": "仿制图章",
        "Clone Stamp (S) · Option-click sets the source": "仿制图章 (S) · 按住 Option 单击设置来源",
        "Close Project": "关闭工程",
        "Color": "颜色",
        "Color Balance": "色彩平衡",
        "Color Burn": "颜色加深",
        "Color Detail": "颜色细节",
        "Color Dodge": "颜色减淡",
        "Color Grading": "颜色分级",
        "Color Mixer": "混色器",
        "Color Overlay": "颜色叠加",
        "Color Picker (Background Color)": "拾色器（背景色）",
        "Color Picker (Foreground Color)": "拾色器（前景色）",
        "Color Picker (Text Color)": "拾色器（文字颜色）",
        "Color Picker (Vignette Color)": "拾色器（暗角颜色）",
        "Color Priority": "颜色优先",
        "Color Range": "色彩范围",
        "Color Range…": "色彩范围…",
        "Color Smoothness": "颜色平滑度",
        "Colorize": "着色",
        "Colors": "颜色",
        "Command Palette": "命令面板",
        "Command Palette…": "命令面板…",
        "Content-Aware Fill": "内容识别填充",
        "Content-Aware Fill…": "内容识别填充…",
        "Contiguous": "连续",
        "Contract…": "收缩…",
        "Contrast": "对比度",
        "Copy": "拷贝",
        "Copy Merged": "合并拷贝",
        "Couldn’t change canvas size": "无法调整画布大小",
        "Couldn’t crop": "无法裁剪",
        "Couldn’t export JPEG": "无法导出 JPEG",
        "Couldn’t export PNG": "无法导出 PNG",
        "Couldn’t open the project": "无法打开工程",
        "Couldn’t paint": "无法绘制",
        "Couldn’t resize the image": "无法调整图像大小",
        "Couldn’t save the project": "无法保存工程",
        "Couldn’t trim image": "无法裁切边缘",
        "Create Clipping Mask": "创建剪贴蒙版",
        "Create a canvas or import an image.": "新建画布或导入图像。",
        "Crop": "裁剪",
        "Crop (C)": "裁剪 (C)",
        "Curves": "曲线",
        "Curves…": "曲线…",
        "Custom": "自定义",
        "Cut": "剪切",
        "Cyan": "青色",
        "Cyans": "青色",
        "Darken": "变暗",
        "Dashed Lines": "虚线",
        "Default colors (D)": "默认颜色 (D)",
        "Dehaze": "去朦胧",
        "Delete": "删除",
        "Delete Layer": "删除图层",
        "Delete Layer Mask": "删除图层蒙版",
        "Delete Layers": "删除图层",
        "Delete Mask": "删除蒙版",
        "Delete Selected Layers": "删除所选图层",
        "Delete selected layer": "删除所选图层",
        "Delete selected layers": "删除所选图层",
        "Density": "浓度",
        "Deselect": "取消选择",
        "Detail": "细节",
        "Difference": "差值",
        "Disable Layer Mask": "停用图层蒙版",
        "Disable Mask": "停用蒙版",
        "Distance": "距离",
        "Distort": "扭曲",
        "Distortion": "畸变",
        "Distribution": "分布",
        "Dither": "抖动",
        "Divide": "划分",
        "Document Bounds": "文档边界",
        "Done": "完成",
        "Don’t Save": "不保存",
        "Dot": "圆点",
        "Dots": "点",
        "Drag to resize the panel": "拖动调整面板大小",
        "Drop Shadow": "投影",
        "Duplicate Layer": "复制图层",
        "Duplicate Layers": "复制图层",
        "Edit": "编辑",
        "Effects": "效果",
        "Ellipse": "椭圆",
        "Elliptical Marquee": "椭圆选框",
        "Enable Layer Mask": "启用图层蒙版",
        "Enable Lens Profile Corrections": "启用镜头配置文件校正",
        "Enable Mask": "启用蒙版",
        "Eraser": "橡皮擦",
        "Exclusion": "排除",
        "Expand…": "扩展…",
        "Export JPEG": "导出 JPEG",
        "Export JPEG…": "导出 JPEG…",
        "Export PNG": "导出 PNG",
        "Export PNG…": "导出 PNG…",
        "Export…": "导出…",
        "Exposure": "曝光",
        "Extension Color": "扩展颜色",
        "Eyedropper": "吸管",
        "Eyedropper (I)": "吸管 (I)",
        "Feather": "羽化",
        "Feather…": "羽化…",
        "File": "文件",
        "Fill": "填充",
        "Fill with Background Color": "以背景色填充",
        "Fill with Foreground Color": "以前景色填充",
        "Filter": "滤镜",
        "Fit": "适合窗口",
        "Fit Canvas": "适合窗口",
        "Fit canvas in window (⌘0)": "画布适合窗口 (⌘0)",
        "Flip Canvas Horizontal": "水平翻转画布",
        "Flip Canvas Vertical": "垂直翻转画布",
        "Flip H": "水平翻转",
        "Flip Horizontal": "水平翻转",
        "Flip V": "垂直翻转",
        "Flip Vertical": "垂直翻转",
        "Flow": "流量",
        "Font": "字体",
        "Font Size": "字号",
        "Foreground": "前景",
        "Foreground color": "前景色",
        "Foreground to Background": "前景色到背景色",
        "Foreground to Transparent": "前景色到透明",
        "Free": "自由",
        "Freehand": "自由绘制",
        "Fuzziness": "颜色容差",
        "Gamma": "伽马",
        "Gaussian": "高斯分布",
        "Gaussian Blur": "高斯模糊",
        "Geometry": "几何",
        "Gradient": "渐变",
        "Gradient (G)": "渐变 (G)",
        "Gradient Map": "渐变映射",
        "Grain": "颗粒",
        "Gray": "灰色",
        "Green": "绿色",
        "Green Primary": "绿色原色",
        "Greens": "绿色",
        "Grid": "网格",
        "Grid Color": "网格颜色",
        "Grid Settings…": "网格设置…",
        "Gridline every": "网格线间隔",
        "Group Layers": "编组图层",
        "Group Selected Layers": "编组所选图层",
        "Group selected layers (⌘G)": "编组所选图层 (⌘G)",
        "Guided": "引导",
        "Guides": "参考线",
        "Hand": "抓手",
        "Hand (H)": "抓手 (H)",
        "Hard Light": "强光",
        "Hard Mix": "实色混合",
        "Hardness": "硬度",
        "Height": "高度",
        "Help": "帮助",
        "Hide All (Black)": "隐藏全部（黑色）",
        "Hide Compositor": "隐藏 Compositor",
        "Hide Others": "隐藏其他应用",
        "High": "高",
        "High quality": "高质量",
        "Highlight Priority": "高光优先",
        "Highlights": "高光",
        "Histogram": "直方图",
        "Horizontal": "水平",
        "Hue": "色相",
        "Hue & Saturation": "色相与饱和度",
        "Hue/Saturation": "色相/饱和度",
        "Image": "图像",
        "Image Size": "图像大小",
        "Image Size…": "图像大小…",
        "Import Image": "导入图像",
        "Import Images": "导入图像",
        "Import Images…": "导入图像…",
        "Import Photoshop File": "导入 Photoshop 文件",
        "Import an image or add a blank layer.": "导入图像或添加空白图层。",
        "Import couldn’t finish": "无法完成导入",
        "Importing images…": "正在导入图像…",
        "Importing…": "正在导入…",
        "Inches": "英寸",
        "Inner Glow": "内发光",
        "Inner Shadow": "内阴影",
        "Input": "输入",
        "Input black": "输入黑场",
        "Input white": "输入白场",
        "Inside": "内部",
        "Intersect": "交集",
        "Inverse": "反向",
        "Invert": "反相",
        "Invert Mask": "反相蒙版",
        "Keep Mine": "保留当前版本",
        "Keyboard Shortcuts": "键盘快捷键",
        "Keyboard Shortcuts…": "键盘快捷键…",
        "Lasso": "套索",
        "Lasso (L)": "套索 (L)",
        "Layer": "图层",
        "Layer Effects": "图层效果",
        "Layer Mask": "图层蒙版",
        "Layer via Copy": "通过拷贝的图层",
        "Layers": "图层",
        "Leading": "行距",
        "Left": "左对齐",
        "Levels": "色阶",
        "Levels…": "色阶…",
        "Lighten": "变亮",
        "Lightness": "明亮度",
        "Line": "直线",
        "Line Spacing": "行距",
        "Linear": "线性",
        "Linear Burn": "线性加深",
        "Linear Dodge (Add)": "线性减淡（添加）",
        "Linear Light": "线性光",
        "Lines": "线条",
        "Link Layer Mask": "链接图层蒙版",
        "Link Mask": "链接蒙版",
        "Linked": "已链接",
        "Liquify": "液化",
        "Load Layer Selection": "载入图层选区",
        "Load Mask Selection": "载入蒙版选区",
        "Loading histogram…": "正在加载直方图…",
        "Lock Guides": "锁定参考线",
        "Low": "低",
        "Luminance": "亮度",
        "Luminance Contrast": "亮度对比度",
        "Luminance Detail": "亮度细节",
        "Luminosity": "明度",
        "Magenta": "洋红色",
        "Magentas": "洋红色",
        "Magic Wand": "魔棒",
        "Magic Wand (W)": "魔棒 (W)",
        "Manual": "手动",
        "Marquee": "选框",
        "Marquee (M)": "选框 (M)",
        "Mask": "蒙版",
        "Masking": "蒙版",
        "Master": "全图",
        "Menus": "菜单",
        "Merge Down": "向下合并",
        "Merge Group": "合并组",
        "Merge Layers": "合并图层",
        "Middle left": "左中",
        "Middle right": "右中",
        "Midtones": "中间调",
        "Millimeters": "毫米",
        "Monochromatic": "单色",
        "Motion Blur": "动感模糊",
        "Move": "移动",
        "Move / Transform": "移动 / 变换",
        "Move / Transform (V)": "移动 / 变换 (V)",
        "Move Layer Down": "下移图层",
        "Move Layer Up": "上移图层",
        "Move Out of Folder": "移出文件夹",
        "Multiply": "正片叠底",
        "Name": "名称",
        "Nearest": "邻近",
        "New": "新建",
        "New Adjustment Layer": "新建调整图层",
        "New Blank Layer": "新建空白图层",
        "New Canvas": "新建画布",
        "New Canvas…": "新建画布…",
        "New Folder": "新建文件夹",
        "New Text Layer": "新建文字图层",
        "New adjustment layer": "新建调整图层",
        "New blank layer": "新建空白图层",
        "New blank layer (⇧⌘N)": "新建空白图层 (⇧⌘N)",
        "New canvas (⌘N)": "新建画布 (⌘N)",
        "New folder": "新建文件夹",
        "No commands match": "没有匹配的命令",
        "No layers yet": "暂无图层",
        "Noise Reduction": "降噪",
        "Normal": "正常",
        "OK": "确定",
        "Object Selection": "对象选择",
        "Off": "关闭",
        "Opacity": "不透明度",
        "Open Project": "打开工程",
        "Open Project…": "打开工程…",
        "Open Recent": "最近打开",
        "Optics": "光学",
        "Oranges": "橙色",
        "Original": "原图",
        "Outer Glow": "外发光",
        "Output": "输出",
        "Output black": "输出黑场",
        "Output white": "输出白场",
        "Outside": "外部",
        "Overlay": "叠加",
        "Pan": "平移",
        "Parametric": "参数",
        "Paste": "粘贴",
        "Percent": "百分比",
        "Pin Light": "点光",
        "Pixel Grid (800% and above)": "像素网格（800% 及以上）",
        "Pixel Shape": "像素形状",
        "Pixel Size": "像素大小",
        "Pixels": "像素",
        "Point": "点",
        "Point Sample": "取样点",
        "Polygonal": "多边形",
        "Polygonal Lasso": "多边形套索",
        "Position": "位置",
        "Preserve Luminosity": "保持明度",
        "Preset": "预设",
        "Preset sizes": "预设尺寸",
        "Press a shortcut": "按下快捷键",
        "Press keys…": "按下组合键…",
        "Preview": "预览",
        "Process": "处理版本",
        "Projection": "投影",
        "Properties": "属性",
        "Purples": "紫色",
        "Quality": "质量",
        "RGB histogram": "RGB 直方图",
        "Radial": "径向",
        "Radius": "半径",
        "Range": "范围",
        "Ratio": "比例",
        "Ready when you are": "准备就绪",
        "Rectangle": "矩形",
        "Rectangular Marquee": "矩形选框",
        "Red": "红色",
        "Red Primary": "红色原色",
        "Redo": "重做",
        "Reds": "红色",
        "Relative to current dimensions": "相对于当前尺寸",
        "Release Clipping Mask": "释放剪贴蒙版",
        "Remove": "移除",
        "Remove Background": "移除背景",
        "Remove Chromatic Aberration": "移除色差",
        "Rename Layer": "重命名图层",
        "Rename Layer…": "重命名图层…",
        "Rename…": "重命名…",
        "Replace": "替换",
        "Resample": "重新采样",
        "Reset": "重置",
        "Resolution": "分辨率",
        "Restore Defaults": "恢复默认设置",
        "Reveal All (White)": "显示全部（白色）",
        "Reverse": "反向",
        "Revert": "恢复",
        "Right": "右对齐",
        "Rotate": "旋转",
        "Rotate Canvas 90° Clockwise": "顺时针旋转画布 90°",
        "Rotate Canvas 90° Counterclockwise": "逆时针旋转画布 90°",
        "Roughness": "粗糙度",
        "Roundness": "圆度",
        "Rulers": "标尺",
        "Sample": "取样",
        "Sample Size": "取样大小",
        "Sampling": "采样",
        "Saturation": "饱和度",
        "Save": "保存",
        "Save As": "另存为",
        "Save As…": "另存为…",
        "Save Project": "保存工程",
        "Save Project As": "工程另存为",
        "Scale": "缩放",
        "Screen": "滤色",
        "Search commands and tools": "搜索命令和工具",
        "Search shortcuts": "搜索快捷键",
        "Select": "选择",
        "Select All": "全选",
        "Select Subject": "选择主体",
        "Select a tool": "选择工具",
        "Selection": "选区",
        "Shadows": "阴影",
        "Shape": "形状",
        "Shape (U) · Shift-U switches Rectangle/Ellipse": "形状 (U) · Shift-U 切换矩形/椭圆",
        "Sharpening": "锐化",
        "Show": "显示",
        "Show All": "显示全部",
        "Show Transform Controls": "显示变换控件",
        "Size": "大小",
        "Smear": "涂抹",
        "Smear (R)": "涂抹 (R)",
        "Smoothing": "平滑",
        "Smudge": "涂抹",
        "Snap": "吸附",
        "Snap To": "吸附到",
        "Soft Light": "柔光",
        "Spacing": "间距",
        "Spot Healing": "污点修复",
        "Spot Healing Brush": "污点修复画笔",
        "Spot Healing Brush (J)": "污点修复画笔 (J)",
        "Spread": "扩展",
        "Square": "方形",
        "Strength": "强度",
        "Stroke": "描边",
        "Style": "样式",
        "Subdivisions": "子网格数量",
        "Subtract": "减去",
        "Subtract from Selection": "从选区减去",
        "Swap foreground and background (X)": "交换前景色和背景色 (X)",
        "Temperature": "色温",
        "Text": "文字",
        "Text Editing": "文字编辑",
        "Text Size": "字号",
        "Text color": "文字颜色",
        "Texture": "纹理",
        "This Layer": "当前图层",
        "Tint": "色调",
        "Tolerance": "容差",
        "Top": "顶部",
        "Top Left Pixel Color": "左上角像素颜色",
        "Top center": "上中",
        "Top left": "左上",
        "Top right": "右上",
        "Tracking": "字距",
        "Transform": "变换",
        "Transform Selection": "变换选区",
        "Transparent": "透明",
        "Transparent Pixels": "透明像素",
        "Trim": "裁切边缘",
        "Trim Away": "裁切方向",
        "Trim…": "裁切边缘…",
        "Two Colors": "双色",
        "Type": "文字",
        "Type (T)": "文字 (T)",
        "Undo": "撤销",
        "Ungroup Layers": "取消图层编组",
        "Uniform": "平均分布",
        "Units": "单位",
        "Unlink Layer Mask": "取消链接图层蒙版",
        "Unlink Mask": "取消链接蒙版",
        "Unsaved changes": "未保存的更改",
        "Untitled": "未命名",
        "Updating…": "正在更新…",
        "Upright": "垂直校正",
        "Vertical": "垂直",
        "Vibrance": "自然饱和度",
        "View": "视图",
        "Vignette": "暗角",
        "Vignetting": "暗角",
        "Vivid Light": "亮光",
        "Wand": "魔棒",
        "White": "白色",
        "White Balance": "白平衡",
        "White · Reveal": "白色 · 显示",
        "Whites": "白色色阶",
        "Width": "宽度",
        "Window": "窗口",
        "Working…": "正在处理…",
        "Yellow": "黄色",
        "Yellows": "黄色",
        "Your changes will be lost if you don’t save them.": "如果不保存，你的更改将丢失。",
        "Zoom": "缩放",
        "Zoom (Z)": "缩放 (Z)",
        "Zoom In": "放大",
        "Zoom Out": "缩小",
        "Zoom in (⌘+)": "放大 (⌘+)",
        "Zoom out (⌘−)": "缩小 (⌘−)",
        "Zoom percentage": "缩放百分比",
        "Zoom percentage (0.1–3200%). Press Return to apply.": "缩放百分比（0.1–3200%）。按回车应用。",
    ]
}
